TYPO3:
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Itc.ITeleTraffic/Private/Form/'
  Neos:
    userInterface:
      inspector:
        dataTypes:
          'TYPO3\Media\Domain\Model\ImageInterface':
            editorOptions:
              features:
                resize: TRUE
